name = "sistema-gestao-gastronomica"
compatibility_date = "2023-07-01"

# Adicione esta linha para o Cloudflare Pages
pages_build_output_dir = "out"

# Mantenha as configurações existentes do D1
[[d1_databases]]
binding = "DB"
database_name = "sistema_gastronomico"
database_id = "512ee40b-67a5-4479-a7dd-908228d57890"
